# ********  DO NOT EDIT THIS FILE  ********
#/******************************************************************************
#  Copyright (C) 2021-2023 Advanced Micro Devices, Inc. All rights reserved.
#*****************************************************************************/
# This file is in Platform\PlatformTools\root_dbuild.sh
python3 Platform/Tools/dbuild/dbuild.py "$@"
