::********  DO NOT EDIT THIS FILE  ********
:: ******************************************************************************
:: * Copyright (C) 2017-2023 Advanced Micro Devices, Inc. All rights reserved.
:: *
:: *******************************************************************************
::This file is in Platform\PlatformTools\root_dbuild.cmd
@ECHO OFF
IF DEFINED PYTHON_HOME (
  "%PYTHON_HOME%\python.exe" Platform\Tools\dbuild\dbuild.py %*
) ELSE (
  Platform\Tools\dbuild\dbuild.py %*
)
